[package]
name = "rush-fuzz"
version = "0.0.1"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4" }
afl = { version = "0.8", optional = true }
# afl = { version = "0.8", features = ["reset_lazy_static"], optional = true }
# afl = { version = "*", features = ["reset_lazy_static"], optional = true }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
# futures = "0.3.9"
tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "time"] }
log = "0.4.14"
# arbitrary = { version = "0.2.0", optional = true }
rush = { path = "..", features = ["fuzz"] }

# [dependencies.rush]
# path = ".."
# features = ["fuzz"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[features]
default = []

[[bin]]
name = "fuzz_target_1"
path = "libfuzz_targets/fuzz_target_1.rs"
test = true
doc = false

[[bin]]
name = "fuzz_target_1_afl"
path = "afl_targets/fuzz_target_1.rs"
# required-features = ["afl", "arbitrary"]
required-features = ["afl"]
# required-features = ["afl"]

# [patch.crates-io]
# # https://github.com/rust-fuzz/afl.rs#lazy_static-variables
# lazy_static = { git = "https://github.com/rust-fuzz/resettable-lazy-static.rs" }


# [package]
# name = "finality-grandpa-fuzz"
# version = "0.0.0"
# authors = ["Automatically generated"]
# publish = false
# edition = "2018"

# [package.metadata]
# cargo-fuzz = true

# [dependencies]
# afl = { version = "0.8", features = ["reset_lazy_static"], optional = true }
# finality-grandpa = { path = "..", features = ["fuzz-helpers"] }
# libfuzzer-sys = "0.3"

# # Prevent this from interfering with workspaces
# [workspace]
# members = ["."]

# [features]
# default = []

# [[bin]]
# name = "round"
# path = "libfuzz_targets/round.rs"

# [[bin]]
# name = "graph"
# path = "libfuzz_targets/graph.rs"

# [[bin]]
# name = "round_afl"
# path = "afl_targets/round.rs"
# required-features = ["afl"]

# [[bin]]
# name = "graph_afl"
# path = "afl_targets/graph.rs"
# required-features = ["afl"]

# [patch.crates-io]
# # https://github.com/rust-fuzz/afl.rs#lazy_static-variables
# lazy_static = { git = "https://github.com/rust-fuzz/resettable-lazy-static.rs" }